### ISSUE TITLE
Updating a Company Contacts email address

### ISSUE THREAD

**Issue by nyteghost** [markciecior/ConnectPyse#15]
How would I go about updating a Contacts email that belongs to a specific company?

**Comment by nyteghost** [comment]
I thought I'd be able to work with this to build off of it. 
`def getContactInfo():
contact_info = contacts_api.contact(url=URL,auth=AUTH)
contact_info = contact_info.get.contacts()

getContactInfo()`

but I get a 'module' object is not callable. Plus I can't seem to find email in contacts.

**Comment by nyteghost** [comment]
So I have gotten this far
`def getContactInfo():
    contact_info = contacts_api.ContactsAPI(url=URL, auth=AUTH)
    contactcomp = contact.Contact()
    contact_info = contact_info.get_contacts()
    ls = list(contact_info)
    for i in ls:
        print(i)
`

That gives me a few random companies. How do I search for a specific company?

**Comment by nyteghost** [comment]
For anyone wanting to search by email

`def getContactInfo():
    ci = contacts_api.ContactsAPI(url=URL, auth=AUTH)
    ci.conditions = 'company/identifier="[Company Name]"'
    # ci.conditions = 'firstName="[First Name]"'
    ci.childconditions= 'communicationItems/value like "[A value, example Email, or Phone Number]"'
    ci = ci.get_contacts()
    ls = list(ci)
    for i in ls:
        print(i)`

**Comment by emichaud** [comment]
@nyteghost

It looks like you made enough progress to meet your needs. I'm curious though what led you to finding and trying the childconditions parameter?

In your example, you set conditions equal to a company name, then childconditions to the contacts email.
This probably limits the result to the company if a matching email is found and it looks like this:

api = contacts_api.ContactsAPI(url=BASE_URL, auth=AUTH)
api.conditions = 'company/name="company" '
api.childconditions = 'communicationItems/value like "email@domain.com" '
api.pageSize = 10
contact_list = api.get_contacts()


Here is an interesting note, If you remove the company filter, this will still work:
api = contacts_api.ContactsAPI(url=BASE_URL, auth=AUTH)
api.childconditions = 'communicationItems/value like "email@domain.com" '
api.pageSize = 10
contact_list = api.get_contacts()

If you change the filter to use conditions and not childconditions then it will not work:
api = contacts_api.ContactsAPI(url=BASE_URL, auth=AUTH)
api.conditions = 'communicationItems/value like "email@domain.com" '
api.pageSize = 10
contact_list = api.get_contacts()

returns:
Server message:{
  "code": "ApiFindCondition",
  "message": "communicationItems/value is not a recognized name."
}

so that email search has to be performed as part of the "childconditions" string with or without a
conditions string in order for it to work.



2 things that I don't understand very well and thought I'd tag on here in case the answers can be provided:

a) How do we know what should be included in api.conditions versus api.childconditions and when to use childconditions versus conditions?

b) On actual dictionary that is returned by CW as part of the contact payload looks like this below:
communicationItems: [{'id': 47128, 'type': {'id': 1, 'name': 'Email', '_info': {'type_href': 'https://csc.x.x/v4_6_release/apis/3.0/company/communicationTypes/1'}}, 'value': 'someone@s.com', 'defaultFlag': True, 'domain': '@h.com', 'communicationType': 'Email'}, {'id': 47129, 'type': {'id': 2, 'name': 'Direct', '_info': {'type_href': 'https://cs.com/v4_6_release/apis/3.0/company/communicationTypes/2'}}, 'value': '9999631', 'defaultFlag': True, 'communicationType': 'Phone'}]

How does "communicationItems/value" work as a filter string when it seems like it should look something like:
"communicationItems/type/_info/value"
but when I try that I get this error message:
Server message:{
  "code": "ApiFindCondition",
  "message": "Invalid field name 'communicationItems/type/_info/value' in childConditions query parameter."
}

compare this to the company name search, which is similar.  CW returns a dictionary with the actual company name in it,
as an example:
company: {'id': 20189, 'identifier': 'N', 'name': 'N', '_info': {'company_href': 'https://c.com/v4_6_release/apis/3.0/company/companies/20189', 'mobileGuid': '50f69b96'}}

which would require a search string like this: 'company/id=20189' or surprisingly this works as well:
'company/_info/mobileGuid="50f69b96"

Is there a question here - lol?
- guidelines for when to use childconditions with or without conditions
- how to best search for subfields using conditions or child conditions

thanks in advance!
Everett

**Comment by emichaud** [comment]
Ok, broke down and read the documentation on CW.  I should have done this sooner.  I was thinking conditions, etc was a nuance of this library when really it's trying to mirror the actual api - so that clears up some confusion on my part.  Also shows I've made it pretty far with just this library and haven't had to go back to CW doc's very often - lol.

here is the link I'm referring to.  they do require a login.
https://developer.connectwise.com/Best_Practices/Manage_API_Requests?mt-learningpath=manage

quick summary:

conditions
Search results based on the fields returned in a GET
Example:
board/name="Integration"
summary="xyz"
board/id in (3, 2, 4)
lastUpdated > [2016-08-20T18:04:26Z]
Only fields returned in a GET request can be used
operators: =, !=, <, <=, >, >=, contains, like, in, not


childConditions
Allows searching arrays on endpoints that list childConditions under parameters
Example:
/company/contacts?childconditions=communicationItems/value like "john@Outlook.com" AND communicationItems/communicationType="Email"
operators: =, !=, <, <=, >, >=, contains, like, in, not

customFieldConditions
Allows searching custom fields when customFieldConditions is listed in the parameters
Example:
/company/contacts?customFieldConditions=caption="TomNumber" AND value !=null
operators: =, !=, <, <=, >, >=, contains, like, in, not

This was interesting to me as I've not spent much time directly with the CW API.  I've used the old reporting api and still do at times but am moving things slowly to REST api.  They also have swagger like definitions of the endpoints and they list out things like conditions, childconditions, customFieldConditions, etc by endpoint.


hope this helps, was informative for me.

**Comment by nyteghost** [comment]
I got this far yesterday

```
def putContactInfo(newValue,CONTACT_ID,ITEM_ID):
    ci = contact_communications_api.ContactCommunicationsAPI(url=URL, auth=AUTH,contact_id=CONTACT_ID)
    VALUE = [
                {
                    'id': ITEM_ID,
                    'type': {
                    'id': 1,
                    'name': 'Email',
                    '_info': {
                        'type_href': 'https://api-na.myconnectwise.net/v4_6_release/apis/3.0//company/communicationTypes/1'
                    }
                    },
                    'value':"'"+newValue+"'",
                    'defaultFlag': True,
                    'domain': 'domain@.com',
                    'communicationType': 'Email'
                }
            ]      
    ci = ci.update_contact_communication(item_id=ITEM_ID,key='communicationItems/communicationType',value=VALUE)
```
    
```
    I have tried many different key(path)= but keep getting 
    Server message:{
  "code": "InvalidPatch",
  "message": "The path '[different paths tried]' is not valid."
}

```

**Comment by nyteghost** [comment]
I got it all figured out. Now trying to figure out how to change the email even if there is a duplicate.

**Comment by nyteghost** [comment]
Unfortunately, due to API restrictions, you can not change the email address to a duplicate of another.
